name: JFrog OIDC Example

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JF_URL: https://trialcjwtjd.jfrog.io/
      BUILD_NAME: krypto-build
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: krypto-data-github-oidc
          oidc-audience: krypto-data-github-oidc

      - name: Create file and upload
        run: |
          echo "hello" > test.txt
          jf rt upload test.txt krypto-data-npm-dev-local/ \
            --build-name="$BUILD_NAME" \
            --build-number="$BUILD_NUMBER"

      - name: Collect build info
        run: |
          jf rt build-collect-env "$BUILD_NAME" "$BUILD_NUMBER"
          jf rt build-add-git "$BUILD_NAME" "$BUILD_NUMBER"
          jf rt build-publish "$BUILD_NAME" "$BUILD_NUMBER"